name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake redis-server nlohmann-json3-dev libhiredis-dev
    
    - name: Start Redis
      run: |
        sudo systemctl start redis-server
        redis-cli ping
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure with CMake
      run: |
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Test build artifacts
      run: |
        cd build
        ls -la server client
